---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################

extends: default

rules:
  braces:
    forbid: non-empty
  brackets:
    forbid: non-empty
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  document-end: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length:
    max: 500
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  quoted-strings:
    quote-type: single
    required: only-when-needed
  trailing-spaces: {}
